### ISSUE TITLE
TLS 1.3?

### ISSUE THREAD

**Issue by CrazyHackGUT** [ErikMinekus/sm-ripext#69] opened 2022-02-16 03:40 UTC
Requests to web-resources that forces TLS 1.3 can be failed with error:
```
  -> SourcePawn_MakeRequest(): base url https://…/api.php, method config
* Hostname … was found in DNS cache
*   Trying 172.67.148.20:443...
* Connected to … (172.67.148.20) port 443 (#1)
* mbedTLS: Connecting to …:443
* mbedTLS: Set min SSL version to TLS 1.0
* ALPN, offering h2
* ALPN, offering http/1.1
* ssl_handshake returned - mbedTLS: (-0x7780) SSL - A fatal alert message was received from our peer
* Closing connection 1
```

TLS 1.2 works normally.

**Comment by ErikMinekus** [comment] 2022-03-17 09:50
Duplicate of #46

**Closed by ErikMinekus** 2022-03-17 09:50 UTC
