### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by CrazyHackGUT** [ErikMinekus/sm-ripext#7] opened 2017-08-10 15:14 UTC
https://crash.limetech.org/eqo3npik5kk2

**Game**: TF2
**Extension version**: 1.0.1

**Comment by ErikMinekus** [comment] 2017-08-14 17:46
Do you have the SourcePawn code that caused the crash?

**Comment by CrazyHackGUT** [comment] 2017-08-15 07:33
Yes.
As it seems to me, the crash is due to this plugin: https://github.com/CrazyHackGUT/Discord/blob/master/addons/sourcemod/scripting/discord_sb.sp
It uses the API of this plugin: https://github.com/CrazyHackGUT/Discord/blob/master/addons/sourcemod/scripting/discord.sp
He collects the request here: https://github.com/CrazyHackGUT/Discord/blob/master/addons/sourcemod/scripting/discord/UTIL.sp#L34-L145

**Comment by kinsi55** [comment] 2017-08-27 18:35
Just had my server segfault because of ripext as well, CS:GO on Linux for me. Unfortunately, i dont have anything that would be useful do debug it, no accelerator, and no idea what could've caused it. The way i use it is that i initialize a global HTTPClient which then executes multiple (only get) requests all the time, some of them do parsing, others are simply "fired and forgot" (empty callback).

How i know it was ripext causing it?

`srcds_linux[12622]: segfault at 0 ip 00000000ea989fb4 sp 00000000ff9ab7e0 error 4 in rip.ext.so[ea977000+b3000]`

**Comment by asherkin** [comment] 2017-08-27 23:16
That is indeed the same crash, they're both crashing around here: https://github.com/ErikMinekus/sm-ripext/blob/edc2f4c91186907b05a2f03fb6ab37540ff08592/extension.cpp#L107-L115

Either `callback` or `forward` is bad (looks like the former, and more likely to be that one, but I can't be 100% without debug symbols).

**Comment by ErikMinekus** [comment] 2017-08-31 07:29
I've added a null check in ```HTTPClient::Request``` and ```ReleaseForward``` calls to [1.0.3](https://github.com/ErikMinekus/sm-ripext/releases/tag/1.0.3). If that doesn't help I'll look into properly terminating threads when plugins are unloaded, instead of abusing the forward system.

**Comment by CrazyHackGUT** [comment] 2017-09-10 14:51
Two new crashes :(
https://crash.limetech.org/rek3l73fgny2
https://crash.limetech.org/mdjtmfvqacos

**Comment by Kentusha** [comment] 2017-09-25 14:43
Extension crash CSGO server

**Comment by CrazyHackGUT** [comment] 2017-10-22 19:28
Any update? :< 
This is great extension. But crashes...

**Comment by CrazyHackGUT** [comment] 2017-10-30 20:50
I fixed this problem in my own fork. Maybe i publish him on AlliedModders during this week.

**Comment by awkspace** [comment] 2017-11-04 21:05
@CrazyHackGUT Why not make a pull request?

**Comment by CrazyHackGUT** [comment] 2017-11-05 09:57
@awkspace I think, developer forget about RiP. You can download my fixed version from [here](https://github.com/CrazyHackGUT/sm-ripext/releases/).

**Comment by peace-maker** [comment] 2018-08-15 12:47
Isn't `std::queue.pop()` destroying the front object?

https://github.com/ErikMinekus/sm-ripext/blob/8b421f292e6cfa6de20fa35878f9502df1e2072a/extension.cpp#L107-L108

@ErikMinekus 
So you're getting a reference to that object and destroy it right away afterwards. Maybe move the `pop()` call after you copied the struct values? I can't reproduce the crash, so can't test it.

**Comment by ErikMinekus** [comment] 2018-08-15 13:35
Hey @peace-maker,

```pop()``` does call the object's destructor. Thanks, I'll try moving it down.

It is indeed difficult to reproduce, it seems to happen at random after running the extension for a while. I figured since the callback is constructed in a separate thread and then passed to the main thread, it was sometimes GCed before it could be processed. But maybe this is the issue instead.

**Comment by asherkin** [comment] 2018-08-15 13:43
> it was sometimes GCed before it could be processed.

There is no garbage collector.

**Comment by wopox1337** [comment] 2019-08-17 08:32
Closed?!

**Closed** 2019-12-21 19:00 UTC
